id: costateixeira.fhir.allergy
canonical: https://costateixeira.github.io/allergy
url: https://costateixeira.github.io/allergy
name: Allergy (Patient Dossier)
title: "Allergy (Patient Dossier)"
description: Allergy (Patient Dossier)
status: active
license: CC0-1.0
date: 2020-02-26
version: 1.0.0
fhirVersion: 4.0.1

copyrightYear: 2021+
releaseLabel: STU1

publisher:
  name: costateixeira
  url: https://www.ehealth.fgov.be/standards/fhir
  email: somewhere@gmail.com

contact:
  - name: Message Structure eHealth
    telecom:
      - system: email
        value: somewhere@gmail.com
        use: work

jurisdiction: urn:iso:std:iso:3166#BE "Belgium"

FSHOnly: false

dependencies: 
  hl7.fhir.uv.sdc: 3.0.0

